portico_home: /home/portico
apps_dir: /home/portico/apps
proxy_dir: /home/portico/reverse-proxy
templates_dir: /home/portico/templates
addons_dir: /home/portico/addons
registry:
  type: internal
  url: localhost:5000
